### ISSUE TITLE
i need a lavalink server

### ISSUE THREAD

**Issue by gomarrota** [saiteja-madha/discord-js-bot#352]
**Describe the bug**
Localhost lavalink does not work anyomore

**Additional context**
I need a lavalink server to use my discord bot and i have no idea how to make one so if anyone can help me showing me how to do it or sending me a lavalink sv ill really appreciate it

**Comment by LeGi0N09** [comment]
```yml
        host: "narco.buses.rocks",
        port: 2269,
        password: "glasshost1984",
        id: "Lavalink Server",
        retryDelay: 5000,
        secure: false,
```
